---
- import_playbook: components/cvmfs.yaml

- hosts: all
  remote_user: "{{ setup_user_name }}"
  become: yes
  become_user: root

  tasks:
      - import_tasks: components/host.yaml
      - import_tasks: components/users.yaml
      - import_tasks: components/builder.yaml builder_headnode_options="--require cctools"

    - name: create wq password
      copy:
          dest: "/etc/vc3-wq.password"
          content: |
              {{ lookup('password', '/dev/null length=64') }}
  
    - name: fetch wq password
      fetch:
        src:  /etc/vc3-wq.password
        dest: "{{ shared_secret_file }}"
        flat: yes

    - name: make secret readable at headnode
      file:
          path: /etc/vc3-wq.password
          owner: root
          group: wheel
          mode: 0644

