---
- import_playbook: components/condor.yaml
- import_playbook: components/cvmfs.yaml

- hosts: all
  remote_user: "{{ setup_user_name }}"
  become: yes
  become_user: root

  tasks:
      - import_tasks: components/host.yaml
      - import_tasks: components/users.yaml
      - import_tasks: components/builder.yaml

