- name: spark login node
  hosts: all
  become: yes
  become_user: root

  tasks:
    - import_tasks: components/minio.yaml
    - import_tasks: components/spark.yaml
    - import_tasks: components/common.yaml

