- import_playbook: components/cvmfs.yaml
- import_playbook: components/condor.yaml

- name: Login + install latest version of Python 3.6, Jupyter, and all required dependencies
  hosts: all
  remote_user: "{{ setup_user_name }}"
  become: yes
  become_user: root

  tasks:
    - import_tasks: components/host.yaml
    - import_tasks: components/users.yaml
    - import_tasks: components/builder.yaml

    - name: Install IUS repo
      yum:
        name: https://centos7.iuscommunity.org/ius-release.rpm
        state: present

    - name: Install python3.6
      yum:
        name: python36u
        state: latest
    
    - name: Install python3.6 dev package
      yum:
        name: python36u-devel
    
    - name: Install pip
      yum:
        name: python36u-pip

    - name: Upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
        executable: pip3.6

    - name: Install node
      yum:
        name: nodejs

    - name: Install configurable-http-proxy
      npm:
        name: configurable-http-proxy
        global: yes
    
    - name: Install jupyterhub
      pip:
        name: jupyterhub
        state: latest
        executable: pip3.6

    - name: Install notebook
      pip:
        name: notebook
        state: latest
        executable: pip3.6

    - name: make dir /etc/.jupyterhub/
      command: mkdir -p '/etc/.jupyterhub'

    - name: Configure jupyter
      copy: src="./config/jupyterhub_config.py"  dest="/etc/.jupyterhub/jupyterhub_config.py"

    - name: Generate openssl certificate
      command: "openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \ -subj '/C=US/ST=Illinois/L=Chicago/O=UoC/CN=notebookserver' \ -keyout /etc/.jupyterhub/jupyterhub.key  -out /etc/.jupyterhub/jupyterhub.crt"

    - name: copy jupyter.service to client
      copy: src="./config/jupyterhub.service"  dest="/usr/lib/systemd/system/jupyterhub.service"

    - name: add to systemctl
      command: systemctl enable jupyterhub.service

    - name: reload systemctl
      command: systemctl daemon-reload
    
    - name: restart systemctl
      command: systemctl restart jupyterhub.service

